package presentacion;

import datos.JuegoSudoku;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import negocio.Iterator;
import negocio.JuegoSesion;
import negocio.JuegoSudokuControlador;

/**
 *
 * @author yarvis
 */
public class Resolver extends javax.swing.JFrame {

    /**
     * Creates new form Resolver
     */
    
    private JuegoSesion sActual;
    private String fileName;
    private File archivo;
    private JuegoSudokuControlador sudokus;
    private Iterator it;
    
    public Resolver(JuegoSesion sActual) {
        this.sActual = sActual;
        sudokus = sActual.getActual();
        
        initComponents();
        if(!sActual.getLogin()){
            saveBtn.setEnabled(false);
        }
        it = new Iterator();
    }

    public Resolver() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findfile = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        fileBtn = new javax.swing.JButton();
        fileTxt = new javax.swing.JTextField();
        solveBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        timeTxt = new javax.swing.JLabel();
        sgteBtn = new javax.swing.JButton();
        preBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        sudokuPanel2 = new presentacion.SudokuPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cargar archivo:");

        fileBtn.setText("Buscar Archivo");
        fileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileBtnActionPerformed(evt);
            }
        });

        solveBtn.setText("Resolver Sudokus");
        solveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Tiempo:");

        sgteBtn.setText("Siguiente Sudoku");
        sgteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgteBtnActionPerformed(evt);
            }
        });

        preBtn.setText("Anterior Sudoku");
        preBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Guardar Actual");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileBtn)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(solveBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sudokuPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sgteBtn)
                                    .addComponent(preBtn)
                                    .addComponent(saveBtn))))
                        .addContainerGap(106, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fileBtn)
                    .addComponent(fileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(solveBtn)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sudokuPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addComponent(preBtn)
                        .addGap(28, 28, 28)
                        .addComponent(sgteBtn)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveBtnActionPerformed

        sudokus.resolverJuegos();
        //System.out.println("Fin resolver");
        it.setList(sudokus.getJuegosArchivo());
        JOptionPane.showMessageDialog(this, "Resolucion terminada!");
    }//GEN-LAST:event_solveBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        sudokus.saveGame(it.actual(),sActual);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void fileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileBtnActionPerformed
        int returnVal = findfile.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            archivo = findfile.getSelectedFile();
            fileName = archivo.getAbsolutePath();
            fileTxt.setText(fileName);
            sudokus.leerArchivo(fileName);
            
        }
    }//GEN-LAST:event_fileBtnActionPerformed

    private void sgteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgteBtnActionPerformed
        JuegoSudoku dj = it.sgte();
        sudokuPanel2.setGame(dj.getSolution());
    }//GEN-LAST:event_sgteBtnActionPerformed

    private void preBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preBtnActionPerformed
        JuegoSudoku dj = it.previo();
        sudokuPanel2.setGame(dj.getSolution());
    }//GEN-LAST:event_preBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resolver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resolver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileBtn;
    private javax.swing.JTextField fileTxt;
    private javax.swing.JFileChooser findfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton preBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton sgteBtn;
    private javax.swing.JButton solveBtn;
    private presentacion.SudokuPanel sudokuPanel2;
    private javax.swing.JLabel timeTxt;
    // End of variables declaration//GEN-END:variables
}
